apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j-secrets-dev
  namespace: argocd
spec:
  destination:
    namespace: data-stores-dev
    server: https://kubernetes.default.svc
  project: cluster-infrastructure
  source:
    helm:
      releaseName: neo4j-secrets-dev
      valueFiles:
      - values.yaml
    path: cluster-infrastructure/dev-test/helm/neo4j-secrets
    repoURL: git@ssh.dev.azure.com:v3/setrans/Azure-Infrastructure/Azure-Infrastructure
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true