apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bioanalyzer-app.configMapName" . }}
  labels:
    {{- include "bioanalyzer-app.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {{- .Values.config.appSettings | toJson | nindent 4 }}