apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j-secrets
  namespace: argocd
spec:
  destination:
    namespace: data-stores
    server: https://kubernetes.default.svc
  project: cluster-infrastructure
  source:
    path: cluster-infrastructure/verida-prod/external-secrets/helm
    repoURL: git@ssh.dev.azure.com:v3/setrans/Azure-Infrastructure/Azure-Infrastructure
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}