<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.1"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5ec44d63-97f8-4688-83d7-b5dc8e5ffb88</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
        <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.4.6" />
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BioAnalyzer.App\BioAnalyzer.App.csproj" />
      <ProjectReference Include="..\BioAnalyzer.EventHandlers\BioAnalyzer.EventHandlers.csproj" />
      <ProjectReference Include="..\BioAnalyzer.Research.Api\BioAnalyzer.Research.Api.csproj" />
    </ItemGroup>

</Project>
