apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetSecretName }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  data:
  {{- range $key, $val := .Values.secretConfig}}
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $val }}
      secretKey: {{ $key}}
  {{- end }}
