apiVersion: v1
kind: Service
metadata:
  name: {{ include "bioanalyzer-research-api.fullname" . }}
  labels:
    {{- include "bioanalyzer-research-api.labels" . | nindent 4 }}
  {{- with (include "bioanalyzer-research-api.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.service.httpsPort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsTargetPort }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "bioanalyzer-research-api.selectorLabels" . | nindent 4 }}