apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bioanalyzer-keyvault
  namespace: bio
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "f4cdabd4-6bba-4b6f-8a20-1f41ffb7369c"
    keyvaultName: "kv-mxinfoappscsi-poc"

    objects:  |
      array:
        - |
          objectName: "ResearchStorage--StorageConnectionString"
          objectAlias: "ResearchStorage--StorageConnectionString"        
          objectType: "secret"                
    tenantId: "38ec304a-0fad-408b-b7cd-e04a2e25b885"
  secretObjects:
  - data:
    - key: ResearchStorage--StorageConnectionString
      objectName: ResearchStorage--StorageConnectionString
    secretName: bioanalyzer-secrets
    type: Opaque
   # resourceGroup: "rg-mxinfo-bioanalyzer-poc-eus" 
   # subscriptionId: "f3b5d6a3-4d2e-4c3a-9e8e-123456789abc" 
   # podIdentityLabel: "azure.workload.identity/client-id" 
   # clientId: "0d0e8878-439d-452a-9735-eb8cfa940c2ec2e" # The client ID of the User Assigned Managed Identity
#    cloudName: ""                             

