apiVersion: v1
kind: Pod
metadata:
  name: busybox-secrets-store-inline
  namespace: bio
  labels:
    azure.workload.identity/use: "true"  # Required if using Azure AD Workload Identity
spec:
  serviceAccountName: mi-bioanalyzer-poc  # Required if using Azure AD Workload Identity
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "sleep", "3600" ]
      env:
        - name: ResearchStorage--StorageConnectionString
          valueFrom:
            secretKeyRef:
              name: bioanalyzer-secrets
              key: ResearchStorage--StorageConnectionString
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "bioanalyzer-keyvault"
  restartPolicy: Never  