neo4j:
  name: "apps-dev"
  minimumClusterSize: 1
  resources:
    cpu: "0.5"
    memory: "2Gi"
  edition: "enterprise"
  password: "my-password"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "dynamic"
    dynamic:
      # * managed-csi-premium provisions premium SSD disks (recommended)
      # * managed-csi provisions standard SSD backed disks
      storageClassName: managed-csi-premium
additionalVolumes:
  - name: neo4j-plugins
    persistentVolumeClaim:
      claimName: neo4j-plugins
additionalVolumeMounts:
  - name: neo4j-plugins
    mountPath: "/var/lib/neo4j/plugins"